import time

def ENCRYPT():
	Password = input("Enter the correct ending phrase: Empires and Kingdoms rise and fall... ")
	if Password == "But the One True King shall still reign.":
		print("Checking typed phrase...")
		time.sleep(4)
		print("Phrase correct. Decrypting message")
		time.sleep(1)
		print("Loading 15%")
		time.sleep(1)
		print("Loading 29%")
		time.sleep(1)
		print("Loading 41%")
		time.sleep(1)
		print("Loading 59%")
		time.sleep(1)
		print("Loading 63%")
		time.sleep(1)
		print("Loading 76%")
		time.sleep(1)
		print("Loading 91%")
		time.sleep(1)
		print("Loading 99%")
		time.sleep(5)
		print("Loading complete. Displaying message now")
		time.sleep(3)
		print("My name is Tensei Matakami. I was a researcher over at Camona Experimental Air Force BASE-01. I don't have much time to explain so listen carefully")
		time.sleep(0.5)
		print('deep breath')
		time.sleep(0.3)
		print("What we were working on over at this base was a superweapon that's far more destructive than the atom bomb, codename 'EA'. It's an orbital weapons platform that uses a subsonic railgun to catapult large rods of tungsten at multiple points across the globe. The destruction that this machine can unleash is catastrophic and can completely erase entire countries off of the map. Needless to say, some of us disagreed on this and have decided to compile all that we know on this project and-")
		time.sleep(10)
		print('CRASH! BAM BAM BAM!')
		time.sleep(2)
		print("Damnit! They're already here! Listen, you must take this to the press and let the world know what's going on over here. I've included all of the blueprints and specs on this weapon in this file. Make sure no one from the government ever gets their hands on this. If they do...")
		time.sleep(7)
		print('SZZZZIIIIIIIIIISSSSSHHH...')
		time.sleep(2.5)
		print("Shit, they've started to cut through the door. Gotta end this message.")
		time.sleep(3)
		return
	else:
		print("Checking type phrase...")
		time.sleep(4)
		print("ERROR: Phrase incorrect. Deleting contents.")
		time.sleep(0.5)
		return
ENCRYPT()
