import time

def Mainstory():
	print("This is a statement")

def StoryIntro():
	PLAYER = False
	
	while PLAYER == False:
		Magus = input("Welcome to the TYPE-CELL Experimental Alter Reality Program. In order to proceed, please enter a new USERNAME: ")
		print("Please wait as the system registers your USERNAME into the DATABASE")
		time.sleep(1)
		print("...")
		time.sleep(1)
		print("...")
		time.sleep(2)
		print("Registration complete. Hello, " + Magus + ", and welcome to the TYPE-CELL Experimental Alter Reality Program. This particular build is equipped with SCENARIO TYPE-A. Would you like to load SCENARIO TYPE-A?")
		time.sleep(0.8)
		PLAY = input("YES/NO: ")
		if PLAY == 'y':
			Transition()
		else:
			print("Very well. Would you like to exit the simulation?")
			time.sleep(1)
			QUIT = input("YES/NO: ")
			if QUIT == 'y':
				break
		PLAYER = False

def Transition():
	print("Confirmation recieved. Initializing Loading Sequence")
	time.sleep(1)
	print("Loading 23%")
	time.sleep(1)
	print("Loading 46%")
	time.sleep(1)
	print("Loading 68%")
	time.sleep(1)
	print("Loading 99%")
	time.sleep(1)
	print("Loading complete")
	time.sleep(0.95)
	print("Initializing simulation")
	time.sleep(3)
	Mainstory()
def Mainstory():
	time.sleep(1.7)
	print("...")
	time.sleep(1.6)
	print("...")
	time.sleep(1.3)
	print("...fire...")
	time.sleep(1.9)
	print("...fire...everywhere...")
	time.sleep(2)
	print("...wha...what...what is...this...")
	time.sleep(2.5)
	print("why... why is there fire... everywhere?")
	time.sleep(2.5)
	print("is... is everyone... dead?")
	time.sleep(1.5)
	print("...no... there has to be someone-")
	time.sleep(1)
	print(" '...no... nii-san...' ")
	time.sleep(0.7)
	print("that voice... coming from that burning house... right in front of-")
	time.sleep(0.9)
	print(" 'nii-san... help...' ")
	time.sleep(1)
	print("laying on the ground, right in front of that house...")
	time.sleep(1.9)
	print("...was a little girl, 8-9 years old. She was face down, looking like she was out of breath. I rushed over to her-")
	time.sleep(4)
	print(" 'Rin-chan!' ")
	time.sleep(1.5)
	print("the words left my mouth without me even thinking about it. wait... who is Rin?")
	time.sleep(3)
	print(" 'nii-san... I... I don't wan't... to die...' ")
	time.sleep(2)
	print("...no... it can't be...")
	time.sleep(1.8)
	print(" 'no! stay alive! just keep breathing! I'll get us out of here...' ")
	time.sleep(3.5)
	print("I... I'm not even controlling my own words...")
	time.sleep(2.7)
	print(" '*cough* nii-san... I'm scared... I don't want to die...' ")
	time.sleep(3.4)
	print("no... I can't let her die... even if she's just a stranger...")
	time.sleep(3)
	print(" '...nii-san...' ")
	time.sleep(1.8)
	print("...no...")
	time.sleep(1.8)
	print(" '...I...love...you' ")
	time.sleep(1.6)
	print("...no...no..no.nononoNONONONO")
	time.sleep(0.7)
	print("YOU CAN'T DIE HERE! NOT YET!")
	time.sleep(1.1)
	print(" 'PLEASE! PLEASE WAKE UP! SAY SOMETHING! PLEASE!' ")
	time.sleep(4)
	print("...")
	time.sleep(2)
	print("...why... why did this happen...")
	time.sleep(2)
	print(" 'WWWHHHHHHHHHYYYYYYYYY!!!!!!!????' ")
	time.sleep(3)
	School()
def School():
	print("*SMACK*")
	time.sleep(0.3)
	print(" 'Owwww....' ")
StoryIntro()
